name: Build Docker Image
run-name: Build ${{ inputs.branch }} - ${{ inputs.user }}

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'GitHub repository to create image off.'
        required: true
        default: 'GIScience/ors-config-migration'
      branch:
        description: 'GitHub branch to create image off.'
        required: true
        default: 'main'
      tag:
        description: 'Name of the docker tag to create.'
        required: true
        default: 'latest'
      user:
        description: ''
        required: false
        default: 'chore'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository || 'GIScience/ors-config-migration' }}
          ref: ${{ inputs.branch || 'main' }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          provenance: false
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ secrets.DOCKER_USERNAME }}/ors-config-migration:${{ inputs.tag || 'latest' }}
