# generated by datamodel-codegen:
#   filename:  application-unittest.yml
#   timestamp: 2024-03-13T11:08:24+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Level(BaseModel):
    org_heigit: Optional[str] = Field(None, alias='org.heigit')


class Logging(BaseModel):
    level: Optional[Level] = None


class Main(BaseModel):
    banner_mode: Optional[str] = Field(None, alias='banner-mode')


class Spring(BaseModel):
    main: Optional[Main] = None


class ConditionItem(BaseModel):
    request_service: Optional[str] = None
    request_profile: Optional[str] = None
    request_preference: Optional[str] = None
    api_format: Optional[str] = None
    api_version: Optional[int] = None
    time_after: Optional[str] = None
    time_before: Optional[str] = None


class Message(BaseModel):
    active: Optional[bool] = None
    text: Optional[str] = None
    condition: Optional[List[ConditionItem]] = None


class Ors(BaseModel):
    messages: Optional[List[Message]] = None


class OrsConfigYML(BaseModel):
    logging: Optional[Logging] = None
    spring: Optional[Spring] = None
    ors: Optional[Ors] = None
